site_name: Excelify
nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - ExcelFrame: excelframe.md
  - Expressions: expressions.md
theme: material
repo_url: https://github.com/yjhan96/excelify

markdown_extensions:
  - toc:
      permalink: true

plugins:
- search
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        options:
          show_source: false
          show_root_heading: false
          show_docstring_examples: true
          show_signature_annotations: true
          separate_signature: true
          line_length: 80
          group_by_category: true
