# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: apps/excelify_viewer/protos/rpc.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'apps/excelify_viewer/protos/rpc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%apps/excelify_viewer/protos/rpc.proto\x12\x03rpc\x1a\x1cgoogle/protobuf/struct.proto\"$\n\rReloadRequest\x12\x13\n\x0bscript_path\x18\x01 \x01(\t\"8\n\x0eReloadResponse\x12&\n\x05table\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct\"&\n\x0fGetSheetRequest\x12\x13\n\x0bscript_path\x18\x01 \x01(\t\":\n\x10GetSheetResponse\x12&\n\x05table\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct\"S\n\x11UpdateCellRequest\x12\x13\n\x0bscript_path\x18\x01 \x01(\t\x12\x1a\n\x03pos\x18\x02 \x01(\x0b\x32\r.rpc.Position\x12\r\n\x05value\x18\x03 \x01(\x02\"<\n\x12UpdateCellResponse\x12&\n\x05table\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct\"&\n\x0fLoadFileRequest\x12\x13\n\x0bscript_path\x18\x01 \x01(\t\":\n\x10LoadFileResponse\x12&\n\x05table\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct\"9\n\x0fSaveFileRequest\x12\x13\n\x0bscript_path\x18\x01 \x01(\t\x12\x11\n\tfile_path\x18\x02 \x01(\t\"\x12\n\x10SaveFileResponse\"$\n\x08Position\x12\x0b\n\x03row\x18\x01 \x01(\x03\x12\x0b\n\x03\x63ol\x18\x02 \x01(\x03\x32\xb7\x02\n\x0e\x45xcelifyViewer\x12\x33\n\x06Reload\x12\x12.rpc.ReloadRequest\x1a\x13.rpc.ReloadResponse\"\x00\x12\x39\n\x08GetSheet\x12\x14.rpc.GetSheetRequest\x1a\x15.rpc.GetSheetResponse\"\x00\x12?\n\nUpdateCell\x12\x16.rpc.UpdateCellRequest\x1a\x17.rpc.UpdateCellResponse\"\x00\x12\x39\n\x08LoadFile\x12\x14.rpc.LoadFileRequest\x1a\x15.rpc.LoadFileResponse\"\x00\x12\x39\n\x08SaveFile\x12\x14.rpc.SaveFileRequest\x1a\x15.rpc.SaveFileResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'apps.excelify_viewer.protos.rpc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RELOADREQUEST']._serialized_start=76
  _globals['_RELOADREQUEST']._serialized_end=112
  _globals['_RELOADRESPONSE']._serialized_start=114
  _globals['_RELOADRESPONSE']._serialized_end=170
  _globals['_GETSHEETREQUEST']._serialized_start=172
  _globals['_GETSHEETREQUEST']._serialized_end=210
  _globals['_GETSHEETRESPONSE']._serialized_start=212
  _globals['_GETSHEETRESPONSE']._serialized_end=270
  _globals['_UPDATECELLREQUEST']._serialized_start=272
  _globals['_UPDATECELLREQUEST']._serialized_end=355
  _globals['_UPDATECELLRESPONSE']._serialized_start=357
  _globals['_UPDATECELLRESPONSE']._serialized_end=417
  _globals['_LOADFILEREQUEST']._serialized_start=419
  _globals['_LOADFILEREQUEST']._serialized_end=457
  _globals['_LOADFILERESPONSE']._serialized_start=459
  _globals['_LOADFILERESPONSE']._serialized_end=517
  _globals['_SAVEFILEREQUEST']._serialized_start=519
  _globals['_SAVEFILEREQUEST']._serialized_end=576
  _globals['_SAVEFILERESPONSE']._serialized_start=578
  _globals['_SAVEFILERESPONSE']._serialized_end=596
  _globals['_POSITION']._serialized_start=598
  _globals['_POSITION']._serialized_end=634
  _globals['_EXCELIFYVIEWER']._serialized_start=637
  _globals['_EXCELIFYVIEWER']._serialized_end=948
# @@protoc_insertion_point(module_scope)
