# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from apps.excelify_viewer.protos import rpc_pb2 as apps_dot_excelify__viewer_dot_protos_dot_rpc__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in apps/excelify_viewer/protos/rpc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ExcelifyViewerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Reload = channel.unary_unary(
                '/rpc.ExcelifyViewer/Reload',
                request_serializer=apps_dot_excelify__viewer_dot_protos_dot_rpc__pb2.ReloadRequest.SerializeToString,
                response_deserializer=apps_dot_excelify__viewer_dot_protos_dot_rpc__pb2.ReloadResponse.FromString,
                _registered_method=True)
        self.GetSheet = channel.unary_unary(
                '/rpc.ExcelifyViewer/GetSheet',
                request_serializer=apps_dot_excelify__viewer_dot_protos_dot_rpc__pb2.GetSheetRequest.SerializeToString,
                response_deserializer=apps_dot_excelify__viewer_dot_protos_dot_rpc__pb2.GetSheetResponse.FromString,
                _registered_method=True)
        self.UpdateCell = channel.unary_unary(
                '/rpc.ExcelifyViewer/UpdateCell',
                request_serializer=apps_dot_excelify__viewer_dot_protos_dot_rpc__pb2.UpdateCellRequest.SerializeToString,
                response_deserializer=apps_dot_excelify__viewer_dot_protos_dot_rpc__pb2.UpdateCellResponse.FromString,
                _registered_method=True)
        self.LoadFile = channel.unary_unary(
                '/rpc.ExcelifyViewer/LoadFile',
                request_serializer=apps_dot_excelify__viewer_dot_protos_dot_rpc__pb2.LoadFileRequest.SerializeToString,
                response_deserializer=apps_dot_excelify__viewer_dot_protos_dot_rpc__pb2.LoadFileResponse.FromString,
                _registered_method=True)
        self.SaveFile = channel.unary_unary(
                '/rpc.ExcelifyViewer/SaveFile',
                request_serializer=apps_dot_excelify__viewer_dot_protos_dot_rpc__pb2.SaveFileRequest.SerializeToString,
                response_deserializer=apps_dot_excelify__viewer_dot_protos_dot_rpc__pb2.SaveFileResponse.FromString,
                _registered_method=True)


class ExcelifyViewerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Reload(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSheet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCell(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExcelifyViewerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Reload': grpc.unary_unary_rpc_method_handler(
                    servicer.Reload,
                    request_deserializer=apps_dot_excelify__viewer_dot_protos_dot_rpc__pb2.ReloadRequest.FromString,
                    response_serializer=apps_dot_excelify__viewer_dot_protos_dot_rpc__pb2.ReloadResponse.SerializeToString,
            ),
            'GetSheet': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSheet,
                    request_deserializer=apps_dot_excelify__viewer_dot_protos_dot_rpc__pb2.GetSheetRequest.FromString,
                    response_serializer=apps_dot_excelify__viewer_dot_protos_dot_rpc__pb2.GetSheetResponse.SerializeToString,
            ),
            'UpdateCell': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCell,
                    request_deserializer=apps_dot_excelify__viewer_dot_protos_dot_rpc__pb2.UpdateCellRequest.FromString,
                    response_serializer=apps_dot_excelify__viewer_dot_protos_dot_rpc__pb2.UpdateCellResponse.SerializeToString,
            ),
            'LoadFile': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadFile,
                    request_deserializer=apps_dot_excelify__viewer_dot_protos_dot_rpc__pb2.LoadFileRequest.FromString,
                    response_serializer=apps_dot_excelify__viewer_dot_protos_dot_rpc__pb2.LoadFileResponse.SerializeToString,
            ),
            'SaveFile': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveFile,
                    request_deserializer=apps_dot_excelify__viewer_dot_protos_dot_rpc__pb2.SaveFileRequest.FromString,
                    response_serializer=apps_dot_excelify__viewer_dot_protos_dot_rpc__pb2.SaveFileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rpc.ExcelifyViewer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rpc.ExcelifyViewer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ExcelifyViewer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Reload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rpc.ExcelifyViewer/Reload',
            apps_dot_excelify__viewer_dot_protos_dot_rpc__pb2.ReloadRequest.SerializeToString,
            apps_dot_excelify__viewer_dot_protos_dot_rpc__pb2.ReloadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSheet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rpc.ExcelifyViewer/GetSheet',
            apps_dot_excelify__viewer_dot_protos_dot_rpc__pb2.GetSheetRequest.SerializeToString,
            apps_dot_excelify__viewer_dot_protos_dot_rpc__pb2.GetSheetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateCell(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rpc.ExcelifyViewer/UpdateCell',
            apps_dot_excelify__viewer_dot_protos_dot_rpc__pb2.UpdateCellRequest.SerializeToString,
            apps_dot_excelify__viewer_dot_protos_dot_rpc__pb2.UpdateCellResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rpc.ExcelifyViewer/LoadFile',
            apps_dot_excelify__viewer_dot_protos_dot_rpc__pb2.LoadFileRequest.SerializeToString,
            apps_dot_excelify__viewer_dot_protos_dot_rpc__pb2.LoadFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rpc.ExcelifyViewer/SaveFile',
            apps_dot_excelify__viewer_dot_protos_dot_rpc__pb2.SaveFileRequest.SerializeToString,
            apps_dot_excelify__viewer_dot_protos_dot_rpc__pb2.SaveFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
